# Generated by Django 5.1.6 on 2025-03-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True, verbose_name='Номер стола')),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Сумма заказа')),
                ('status', models.CharField(choices=[('0', 'В ожидании'), ('1', 'Оплачено'), ('2', 'Готово')], default='0', max_length=1)),
                ('menu_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['table_number'],
            },
        ),
    ]
