# Generated by Django 5.1.6 on 2025-03-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu_order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'В ожидании'), ('1', 'Оплачено'), ('2', 'Готово')], default='0', max_length=1, verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='menu_order',
            field=models.ManyToManyField(related_name='menu_order', to='order.menu', verbose_name='Меню заказа'),
        ),
    ]
